//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.OrderGoods = new HashSet<OrderGood>();
        }
    
        public int Id { get; set; }
        public string Sale { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> GoodsCategoryId { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual GoodsCategory GoodsCategory { get; set; }
        public virtual ImageJournal ImageJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderGood> OrderGoods { get; set; }
    }
}
