//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderGoods = new HashSet<OrderGood>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> IssuePointId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ReceiveCode { get; set; }
        public string Status { get; set; }
    
        public virtual IssuePoint IssuePoint { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderGood> OrderGoods { get; set; }
    }
}
